/**
* NW Healthcheck API
* NW Healthcheck API - to run test and ensure its running ok
*
* OpenAPI spec version: 1.0
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


package model

import enumeratum._

//import co.nextwireless.healthchecker.ws._

/**
 * @param id 
 * @param description 
 * @param result 
 * @param fail_message 
 */
    case class Check (
        id: CheckId,
        description: String,
        result: Check.ResultEnum,
        fail_message: Option[String]
    )

object Check {
sealed trait ResultEnum extends EnumEntry
object ResultEnum extends Enum[ResultEnum] with CirceEnum[ResultEnum] {
val values = findValues
  case object success extends ResultEnum
  case object fail extends ResultEnum

}

    }


