/**
* NW Healthcheck API
* NW Healthcheck API - to run test and ensure its running ok
*
* OpenAPI spec version: 1.0
*
*
* NOTE: This class is auto generated by the swagger code generator program.
* https://github.com/swagger-api/swagger-codegen.git
* Do not edit the class manually.
*/


package model

//import co.nextwireless.healthchecker.ws._
import enumeratum._

/**
 * @param ws_id 
 * @param checks 
 */
    case class Healthcheck (
        ws_id: Healthcheck.WsIdEnum,
        checks: List[Check]
    )

object Healthcheck {
sealed trait WsIdEnum extends EnumEntry
object WsIdEnum extends Enum[WsIdEnum] with CirceEnum[WsIdEnum] {
val values = findValues
  case object mde_amazon extends WsIdEnum
  case object mde_prestashop extends WsIdEnum
  case object mde_ebay extends WsIdEnum
  case object mde_aliexpress extends WsIdEnum
  case object mde_hubx extends WsIdEnum
  case object mde_mobileclub extends WsIdEnum
  case object mde_mirakl extends WsIdEnum
  case object warranty extends WsIdEnum
  case object tester_kpi extends WsIdEnum

}

    }


